### ISSUE TITLE
On server start should display the port server is listening on

### ISSUE THREAD

**Issue by AbdullahChaudhry** [FAC-11/the-ticket-bank#31]
Currently when the server starts it's not intuitive which port it's listening on

**Comment by oliverjam** [comment]
Sorry for the drive-by comment but I saw the repo on Gitter 😄 

It's a little thing but it's nice for the server to log a full address (with the `http://`) so that users with editors have clickable URLs can just click and go straight to the page. It always frustrates me a bit when I have to type it rather than click 😉
